pool:
  vmImage: ubuntu-latest

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: Pay-As-You-Go
  appName: FHLBC
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: "Setting Python version to 3.7 as required by functions"
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'
- bash: |
    if [ -f extensions.csproj ]
    then
        dotnet build extensions.csproj --output ./bin
    fi
    pip install --target="./.python_packages/lib/site-packages" -r ./python/simple/functionApp/Application/requirements.txt
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    artifactName: 'drop'
  
- task: AzureFunctionApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: FHLBC1-SC
    appType: functionAppLinux # default is functionApp
    appName: $(appName)
    package: $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip
    #Uncomment the next lines to deploy to a deployment slot
    #Note that deployment slots is not supported for Linux Dynamic SKU
    deployToSlotOrASE: true
    resourceGroupName: 'FHLBC'
    slotName: 'fhlbc-cin'